### ISSUE TITLE
ChannelState is returning as null on the channel

### ISSUE THREAD

**Issue by luvishq** [GetStream/stream-chat-dart#92]
I am getting NPE while trying to fetch a list of message from the channel. Below are the steps i followed:
1. 
```dart
Future<Channel> createChannel({
    List<String> idMembers,
  }) async {
    final channel =
        _client.channel('messaging', extraData: {"members": idMembers});

    await channel.create();
    _currentChannel = channel;
    _currentChannel.watch();
    debugPrint("The channel got created" + _currentChannel.id);
    updateChannel(_currentChannel);
    return _currentChannel;
  }
```
The channel got created , checked in the explorer as well.

2. On the front end, I did the below 
```dart
class IndividualChat extends StatefulWidget {
  final String userId;

  IndividualChat({@required this.userId});

  @override
  _IndividualChatState createState() => _IndividualChatState();
}

class _IndividualChatState extends State<IndividualChat> {
  ChatService chatService;
  Channel currentChannel;
  Client client;
  bool changeState;

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
  }

  // var message = Message();
  @override
  Widget build(BuildContext context) {
    chatService = Provider.of<ChatService>(context);
    client = chatService.getClient();
    currentChannel = chatService.getChannel();
    debugPrint("The channel got created fdsdds state"+ currentChannel.state.toString());
    final messages = currentChannel.state.channelStateStream;
    return Scaffold(
      appBar: AppBar(
        title: Text('Channel: ${currentChannel.id}'),
      ),
      body: SafeArea(
        child: StreamBuilder<ChannelState>(
          stream: messages,
          builder: (
              BuildContext context,
              AsyncSnapshot<ChannelState> snapshot,
              ) {
            if (snapshot.hasData && snapshot.data != null) {
               debugPrint("We have messages");
            } else if (snapshot.hasError) {
              return const Center(
                child: Text(
                  'There was an error loading messages. Please see logs.',
                ),
              );
            }
            return const Center(
              child: SizedBox(
                width: 100.0,
                height: 100.0,
                child: CircularProgressIndicator(),
              ),
            );
          },
        ),
      ),
    );
  }
}

```
I am getting the below exception on the screen:

```
I/flutter (20477): The channel got created fdsdds statenull
I/flutter (20477): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (20477): The following NoSuchMethodError was thrown building IndividualChat(dirty, dependencies:
I/flutter (20477): [_InheritedProviderScope<ChatService>], state: _IndividualChatState#61d9f):
I/flutter (20477): The getter 'channelStateStream' was called on null.
I/flutter (20477): Receiver: null
I/flutter (20477): Tried calling: channelStateStream
I/flutter (20477): 
I/flutter (20477): The relevant error-causing widget was:
I/flutter (20477):   IndividualChat
I/flutter (20477):   file:///Users/laavaans/AndroidStudioProjects/limobile/lib/components/recent_chats.dart:56:43
I/flutter (20477): 
I/flutter (20477): When the exception was thrown, this was the stack:
I/flutter (20477): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
I/flutter (20477): #1      _IndividualChatState.build (package:flutter_app/chats/models/individual_chat.dart:36:43)
I/flutter (20477): #2      StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
I/flutter (20477): #3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
I/flutter (20477): #4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (20477): #5      Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (20477): #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
I/flutter (20477): #7      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
I/flutter (20477): #8      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
I/flutter (20477): ...     Normal element mounting (132 frames)
I/flutter (20477): #140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (20477): #141    Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
I/flutter (20477): #142    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5705:32)
I/flutter (20477): #143    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6246:17)
I/flutter (20477): #144    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (20477): #145    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (20477): #146    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (20477): #147    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (20477): #148    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
I/flutter (20477): #149    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (20477): #150    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (20477): #151    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (20477): #152    ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
I/flutter (20477): #153    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:183:11)
I/flutter (20477): #154    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (20477): #155    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
I/flutter (20477): #156    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (20477): #157    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (20477): #158    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (20477): #159    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (20477): #160    StatefulElement.update (package:flutter/src/widgets/framework.dart:4832:5)
I/flutter (20477): #161    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (20477): #162    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
I/flutter (20477): #163    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (20477): #164    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6125:14)
I/flutter (20477): #165    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (20477): #166    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (20477): #167    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (20477): #168    StatelessElement.update (package:flutter/src/widgets/framework.dart:4708:5)
I/flutter (20477): #169    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (20477): #170    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (20477): #171    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (20477): #172    ProxyElement.update (package:flutter/src/widgets/framework.dart:4987:5)
I/flutter (20477): #173    Element.updateChild (package:flutter/src/widgets/framework.dart:3314:15)
I/flutter (20477): #174    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (20477): #175    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (20477): #176    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (20477): #177    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
I/flutter (20477): #178    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
I/flutter (20477): #179    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
I/flutter (20477): #180    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (20477): #181    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (20477): #182    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
I/flutter (20477): #186    _invoke (dart:ui/hooks.dart:251:10)
I/flutter (20477): #187    _drawFrame (dart:ui/hooks.dart:209:3)
I/flutter (20477): (elided 3 frames from dart:async)
I/flutter (20477): 
I/flutter (20477): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (20477): (2021-02-15 00:33:19.448463) ℹ️ 📡 Query channel start
I/flutter (20477): (2021-02-15 00:33:19.476293) ℹ️ 📡     
I/flutter (20477):           method: GET
I/flutter (20477):     
I/flutter (20477):         
```

Can someone help me in pointing out what is going wrong with my implementation ?

gz#9405

**Comment by SeniYG** [comment]
Hi,

It looks like something is wrong with ChatService, as I believe this `final messages = currentChannel.state.channelStateStream;` is returning undefined or null object for messages.
Are you sure both of these calls return non-empty object? 
```
 client = chatService.getClient();
 currentChannel = chatService.getChannel();
```

**Comment by luvishq** [comment]
I figured out the issue was that i was trying different packages and mixed up calling different instances. It works now. Thanks a lot :)
